### ISSUE TITLE
Cannot launch SXOS with SX Gear

### ISSUE THREAD

**Issue by Smelltastic** [Guillem96/argon-nx#26]
ArgonNX's SXOS launcher appears to look for SX's \boot.dat. Unfortunately that creates a problem.
With SX OS installed as \boot.dat, I can only boot to SX OS, then have to go through its payload launcher to kick off ArgonNX.
With SX Gear installed as \boot.dat, I can run ArgonNX directly as \payload.bin, but then it can't run SX OS, because the \boot.dat is the SX Gear version.

It would be awesome if ArgonNX could look for some file *other* than \boot.dat to launch SX OS. That way I can boot straight into ArgonNX and still be able to use SX OS. If I have to boot into SX OS and use its payload launcher first, there's little reason to use ArgonNX.

**Comment by justin-parker** [comment]
This isn't an ArgonNX issue.  Argon is just listing all your .bins that are in the payloads directory.  The issue is with SXOS.  I run SXOS, but do NOT use SX Gear or SX Pro dongle (I am using an R4S).   Like you described, SX's solution to launching 3rd party CFW is to use its boot loader menu (hold vol+ when booting SX OS), or using the alternate BOOT.DAT which just looks for a payload.bin.

Again, this is not an issue with ArgonNX.   ArgonNX is just launching the stage one payload for SX OS, which in turn is loading boot.dat (and since you are using the alternate version of this with sx gear or pro, will just load payload.bin, and not the sxos).
